# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f1645a03b864b25420cc2b2fb6efdd7d2372b6b13dbac2c7dc01adb95d016bb9b6a6347b5b3f13a2d7758a45f5574afe66c65d34665d5f4b62b8eb0114396a4

test:
  secret_key_base: 3eafc9bfb4e7146e67191740f92dc8a5eb53107c8ba96a4316bdce1e4894a7e20bc220fb85020c82a219c47a239a2763f93ffc1b4e59ff147632c02fdbfc3fd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
